openapi: 3.1.0

info:
  title: Gilded Rose Inventory API
  description: |
    Contract-first API for managing inventory items.
    This specification defines HTTP semantics, error models,
    and response shapes. No implementation is assumed.
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  /items:
    get:
      summary: List all items
      operationId: listItems
      responses:
        "200":
          description: A list of inventory items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
              examples:
                success:
                  value:
                    - id: "item-1"
                      name: "Aged Brie"
                      sell_in: 10
                      quality: 20
        "500":
          $ref: "#/components/responses/InternalServerError"

    post:
      summary: Create a new item
      operationId: createItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemCreate"
            examples:
              valid:
                value:
                  name: "Elixir of the Mongoose"
                  sell_in: 5
                  quality: 7
      responses:
        "201":
          description: Item created
          headers:
            Location:
              description: URL of the created item
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /items/{itemId}:
    parameters:
      - name: itemId
        in: path
        required: true
        schema:
          type: string

    get:
      summary: Get a single item
      operationId: getItem
      responses:
        "200":
          description: Item found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

    patch:
      summary: Update an item
      operationId: updateItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ItemUpdate"
      responses:
        "200":
          description: Item updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          $ref: "#/components/responses/InvalidInput"
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: Delete an item
      operationId: deleteItem
      responses:
        "204":
          description: Item deleted successfully
        "404":
          $ref: "#/components/responses/ItemNotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  schemas:
    Item:
      type: object
      required: [id, name, sell_in, quality]
      properties:
        id:
          type: string
        name:
          type: string
        sell_in:
          type: integer
        quality:
          type: integer
          minimum: 0
          maximum: 50

    ItemCreate:
      type: object
      required: [name, sell_in, quality]
      properties:
        name:
          type: string
        sell_in:
          type: integer
        quality:
          type: integer
          minimum: 0
          maximum: 50

    ItemUpdate:
      type: object
      properties:
        sell_in:
          type: integer
        quality:
          type: integer
          minimum: 0
          maximum: 50

    Problem:
      type: object
      required: [type, title, status]
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
          format: uri

  responses:
    InvalidInput:
      description: Invalid request payload
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
          examples:
            invalid:
              value:
                type: "https://example.com/problems/invalid-input"
                title: "Invalid input"
                status: 400
                detail: "Quality must be between 0 and 50"

    ItemNotFound:
      description: Item not found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
          examples:
            notFound:
              value:
                type: "https://example.com/problems/item-not-found"
                title: "Item not found"
                status: 404
                detail: "Item with given id does not exist"

    InternalServerError:
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Problem"
          examples:
            serverError:
              value:
                type: "https://example.com/problems/internal-error"
                title: "Internal server error"
                status: 500
